name: kgamepedia
description: Kgamepedia App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  http: ^0.13.4
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.0
  tab_indicator_styler: ^2.0.0
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.13
  splash_screen_view: ^3.0.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  pie_chart: ^5.3.0
  animations: ^2.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/user_avatars/

